# Generates GitVersion.cs (AssemblyVersion) and QuickLook.Plugin.Metadata.config
# from the current git tag/commit. Both outputs are gitignored and regenerated
# on every build (also in CI).

$revision = (git describe --always --tags) 2>$null
if (-not $revision) { $revision = '0.0.0' }

$tag = (git describe --always --tags --abbrev=0) 2>$null

# AssemblyVersion must be a plain dotted number (e.g. 1.2.3). Strip a leading "v"
# (so conventional tags like v0.2.0 work) and fall back to 0.0.0 otherwise.
$ver = if ($tag) { $tag -replace '^[vV]', '' } else { '0.0.0' }
if ($ver -notmatch '^[0-9]+(\.[0-9]+){0,3}$') { $ver = '0.0.0' }

$text = @"
// This file is generated by update-version.ps1

using System.Reflection;

[assembly: AssemblyVersion("$ver")]
[assembly: AssemblyInformationalVersion("$revision")]
"@

$text | Out-File $PSScriptRoot\..\GitVersion.cs -Encoding utf8

$xml = [xml](Get-Content $PSScriptRoot\..\QuickLook.Plugin.Metadata.Base.config)
$xml.Metadata.Version = "$revision"
$xml.Save("$PSScriptRoot\..\QuickLook.Plugin.Metadata.config")
